"""Added branch and change relationship in education

Revision ID: 00986b6201c7
Revises: b3c0659afcf8
Create Date: 2022-07-29 22:27:56.599664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00986b6201c7'
down_revision = 'b3c0659afcf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student', sa.Column('branch_id', sa.String(length=50), nullable=True))
    op.drop_constraint('dy_sms_student_ibfk_2', 'dy_sms_student', type_='foreignkey')
    op.create_foreign_key(None, 'dy_sms_student', 'dy_shared_branch', ['branch_id'], ['id'])
    op.drop_column('dy_sms_student', 'education_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student', sa.Column('education_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'dy_sms_student', type_='foreignkey')
    op.create_foreign_key('dy_sms_student_ibfk_2', 'dy_sms_student', 'dy_shared_education', ['education_id'], ['id'])
    op.drop_column('dy_sms_student', 'branch_id')
    # ### end Alembic commands ###
