"""Added some tables

Revision ID: 1579675c8738
Revises: 7645a531e14d
Create Date: 2022-07-28 14:40:49.330193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1579675c8738'
down_revision = '7645a531e14d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
