"""Added level table2

Revision ID: 23a0a4f322c5
Revises: f158789d66bc
Create Date: 2022-07-17 02:50:19.219399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a0a4f322c5'
down_revision = 'f158789d66bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
