"""rename updated date

Revision ID: 2b4c501992e6
Revises: 6343fee0bcbb
Create Date: 2022-07-30 00:05:21.068339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b4c501992e6'
down_revision = '6343fee0bcbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_shared_branch', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('dy_shared_branch', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_shared_branch', sa.Column('update_date', mysql.DATETIME(), nullable=True))
    op.drop_column('dy_shared_branch', 'updated_date')
    # ### end Alembic commands ###
