"""Increase password size

Revision ID: 2e59cd5598c5
Revises: 96805f50a4f1
Create Date: 2022-07-17 03:08:51.195005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e59cd5598c5'
down_revision = '96805f50a4f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
