"""Testing

Revision ID: 3f7dafad9c70
Revises: ef880395ae97
Create Date: 2022-07-24 14:50:06.770327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f7dafad9c70'
down_revision = 'ef880395ae97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student_class_link', sa.Column('left_id_testing', sa.String(length=50), nullable=True))
    op.add_column('dy_sms_student_class_link', sa.Column('right_id', sa.String(length=50), nullable=True))
    op.drop_constraint('dy_sms_student_class_link_ibfk_2', 'dy_sms_student_class_link', type_='foreignkey')
    op.drop_constraint('dy_sms_student_class_link_ibfk_1', 'dy_sms_student_class_link', type_='foreignkey')
    op.create_foreign_key(None, 'dy_sms_student_class_link', 'dy_sms_student', ['left_id_testing'], ['id'])
    op.create_foreign_key(None, 'dy_sms_student_class_link', 'dy_sms_class', ['right_id'], ['id'])
    op.drop_column('dy_sms_student_class_link', 'student_id')
    op.drop_column('dy_sms_student_class_link', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student_class_link', sa.Column('class_id', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('dy_sms_student_class_link', sa.Column('student_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'dy_sms_student_class_link', type_='foreignkey')
    op.drop_constraint(None, 'dy_sms_student_class_link', type_='foreignkey')
    op.create_foreign_key('dy_sms_student_class_link_ibfk_1', 'dy_sms_student_class_link', 'dy_sms_student', ['student_id'], ['id'])
    op.create_foreign_key('dy_sms_student_class_link_ibfk_2', 'dy_sms_student_class_link', 'dy_sms_class', ['class_id'], ['id'])
    op.drop_column('dy_sms_student_class_link', 'right_id')
    op.drop_column('dy_sms_student_class_link', 'left_id_testing')
    # ### end Alembic commands ###
