"""Added class table2

Revision ID: 4f6796143805
Revises: d8b90b5696ef
Create Date: 2022-07-24 14:30:08.214999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6796143805'
down_revision = 'd8b90b5696ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
