"""Change user relatinship

Revision ID: 5f5195aae28a
Revises: a6e5ae3f4c5b
Create Date: 2022-07-24 15:01:40.858521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5195aae28a'
down_revision = 'a6e5ae3f4c5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
