"""Fixed relationship

Revision ID: 600c62a61d7f
Revises: 5f5195aae28a
Create Date: 2022-07-24 15:06:29.138216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600c62a61d7f'
down_revision = '5f5195aae28a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
