"""Rename updated_date

Revision ID: 6343fee0bcbb
Revises: e8cabb3ed1ca
Create Date: 2022-07-29 23:59:00.468975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6343fee0bcbb'
down_revision = 'e8cabb3ed1ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_guardian', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('dy_sms_guardian', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_guardian', sa.Column('update_date', mysql.DATETIME(), nullable=True))
    op.drop_column('dy_sms_guardian', 'updated_date')
    # ### end Alembic commands ###
