"""Added association table4

Revision ID: 64985f9ca324
Revises: de107c821706
Create Date: 2022-07-24 14:44:07.823308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64985f9ca324'
down_revision = 'de107c821706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
