"""Rename updated date employee

Revision ID: 73e569f7e45d
Revises: 04963f601b9a
Create Date: 2022-07-30 08:48:38.791889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73e569f7e45d'
down_revision = '04963f601b9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_employee', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('dy_sms_employee', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_employee', sa.Column('update_date', mysql.DATETIME(), nullable=True))
    op.drop_column('dy_sms_employee', 'updated_date')
    # ### end Alembic commands ###
