"""Added some tables

Revision ID: 7645a531e14d
Revises: 8a394ebe742f
Create Date: 2022-07-28 14:35:03.824222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7645a531e14d'
down_revision = '8a394ebe742f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_level', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('dy_sms_package', sa.Column('level_id', sa.String(length=50), nullable=True))
    op.add_column('dy_sms_package', sa.Column('package_set_id', sa.String(length=50), nullable=True))
    op.add_column('dy_sms_package', sa.Column('subject_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'dy_sms_package', 'dy_sms_package_set', ['package_set_id'], ['id'])
    op.create_foreign_key(None, 'dy_sms_package', 'dy_sms_subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'dy_sms_package', 'dy_sms_level', ['level_id'], ['id'])
    op.drop_constraint('dy_sms_student_ibfk_5', 'dy_sms_student', type_='foreignkey')
    op.drop_column('dy_sms_student', 'package_set_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student', sa.Column('package_set_id', mysql.VARCHAR(length=50), nullable=True))
    op.create_foreign_key('dy_sms_student_ibfk_5', 'dy_sms_student', 'dy_sms_package', ['package_set_id'], ['id'])
    op.drop_constraint(None, 'dy_sms_package', type_='foreignkey')
    op.drop_constraint(None, 'dy_sms_package', type_='foreignkey')
    op.drop_constraint(None, 'dy_sms_package', type_='foreignkey')
    op.drop_column('dy_sms_package', 'subject_id')
    op.drop_column('dy_sms_package', 'package_set_id')
    op.drop_column('dy_sms_package', 'level_id')
    op.drop_column('dy_sms_level', 'rank')
    # ### end Alembic commands ###
