"""Added created_date, updated_date

Revision ID: 7a0fdea5d76c
Revises: 600c62a61d7f
Create Date: 2022-07-24 20:40:06.077124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0fdea5d76c'
down_revision = '600c62a61d7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_shared_user', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dy_shared_user', 'updated_date')
    # ### end Alembic commands ###
