"""added level table

Revision ID: 96805f50a4f1
Revises: fdd293bca0f9
Create Date: 2022-07-17 02:55:44.908690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96805f50a4f1'
down_revision = 'fdd293bca0f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
