"""Upgrade amount length payment

Revision ID: 96f8e58cd8de
Revises: 999f4431afcc
Create Date: 2022-07-30 09:00:48.005264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f8e58cd8de'
down_revision = '999f4431afcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
