"""Rename updated date payment

Revision ID: 999f4431afcc
Revises: 9c29641a9114
Create Date: 2022-07-30 08:58:25.419610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '999f4431afcc'
down_revision = '9c29641a9114'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_payment', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('dy_sms_payment', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_payment', sa.Column('update_date', mysql.DATETIME(), nullable=True))
    op.drop_column('dy_sms_payment', 'updated_date')
    # ### end Alembic commands ###
