"""Rename updated date package set

Revision ID: 9c29641a9114
Revises: 73e569f7e45d
Create Date: 2022-07-30 08:55:12.643397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c29641a9114'
down_revision = '73e569f7e45d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_package_set', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('dy_sms_package_set', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_package_set', sa.Column('update_date', mysql.DATETIME(), nullable=True))
    op.drop_column('dy_sms_package_set', 'updated_date')
    # ### end Alembic commands ###
