"""Change updated date

Revision ID: 9f87cecf54ae
Revises: 96f8e58cd8de
Create Date: 2022-07-30 09:20:31.594004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f87cecf54ae'
down_revision = '96f8e58cd8de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_package', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.drop_column('dy_sms_package', 'update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_package', sa.Column('update_date', mysql.DATETIME(), nullable=True))
    op.drop_column('dy_sms_package', 'updated_date')
    # ### end Alembic commands ###
