"""Added level table4

Revision ID: a185a3714b8b
Revises: a9fbb37c302c
Create Date: 2022-07-17 02:51:23.280661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a185a3714b8b'
down_revision = 'a9fbb37c302c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
