"""Change student id

Revision ID: a6e5ae3f4c5b
Revises: d60000c6a190
Create Date: 2022-07-24 15:00:16.565272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e5ae3f4c5b'
down_revision = 'd60000c6a190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
