"""Added level table3

Revision ID: a9fbb37c302c
Revises: 23a0a4f322c5
Create Date: 2022-07-17 02:50:51.199163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fbb37c302c'
down_revision = '23a0a4f322c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
