"""Modify guardian table

Revision ID: af62439c9a8c
Revises: 00986b6201c7
Create Date: 2022-07-29 22:40:13.451966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af62439c9a8c'
down_revision = '00986b6201c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_guardian', sa.Column('primary_user_id', sa.String(length=50), nullable=True))
    op.add_column('dy_sms_guardian', sa.Column('secondary_user_name', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'dy_sms_guardian', 'dy_shared_user', ['secondary_user_name'], ['id'])
    op.create_foreign_key(None, 'dy_sms_guardian', 'dy_shared_user', ['primary_user_id'], ['id'])
    op.drop_column('dy_sms_guardian', 'secondary_name')
    op.drop_column('dy_sms_guardian', 'primary_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_guardian', sa.Column('primary_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('dy_sms_guardian', sa.Column('secondary_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'dy_sms_guardian', type_='foreignkey')
    op.drop_constraint(None, 'dy_sms_guardian', type_='foreignkey')
    op.drop_column('dy_sms_guardian', 'secondary_user_name')
    op.drop_column('dy_sms_guardian', 'primary_user_id')
    # ### end Alembic commands ###
