"""Modify guardian table2

Revision ID: b302f00e7b90
Revises: af62439c9a8c
Create Date: 2022-07-29 22:41:05.819100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b302f00e7b90'
down_revision = 'af62439c9a8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_guardian', sa.Column('secondary_user_id', sa.String(length=50), nullable=True))
    op.drop_constraint('dy_sms_guardian_ibfk_1', 'dy_sms_guardian', type_='foreignkey')
    op.create_foreign_key(None, 'dy_sms_guardian', 'dy_shared_user', ['secondary_user_id'], ['id'])
    op.drop_column('dy_sms_guardian', 'secondary_user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_guardian', sa.Column('secondary_user_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'dy_sms_guardian', type_='foreignkey')
    op.create_foreign_key('dy_sms_guardian_ibfk_1', 'dy_sms_guardian', 'dy_shared_user', ['secondary_user_name'], ['id'])
    op.drop_column('dy_sms_guardian', 'secondary_user_id')
    # ### end Alembic commands ###
