"""Added created and updated

Revision ID: b3c0659afcf8
Revises: 1579675c8738
Create Date: 2022-07-28 18:57:01.224293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c0659afcf8'
down_revision = '1579675c8738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_class', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_class', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_guardian', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_guardian', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_level', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_level', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_package', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_package', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_package_set', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_package_set', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_subject', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_subject', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dy_sms_subject', 'updated_date')
    op.drop_column('dy_sms_subject', 'created_date')
    op.drop_column('dy_sms_package_set', 'update_date')
    op.drop_column('dy_sms_package_set', 'created_date')
    op.drop_column('dy_sms_package', 'update_date')
    op.drop_column('dy_sms_package', 'created_date')
    op.drop_column('dy_sms_level', 'updated_date')
    op.drop_column('dy_sms_level', 'created_date')
    op.drop_column('dy_sms_guardian', 'update_date')
    op.drop_column('dy_sms_guardian', 'created_date')
    op.drop_column('dy_sms_class', 'updated_date')
    op.drop_column('dy_sms_class', 'created_date')
    # ### end Alembic commands ###
