"""Added date for Student

Revision ID: c04bca259ef5
Revises: 7a0fdea5d76c
Create Date: 2022-07-24 21:34:04.450700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04bca259ef5'
down_revision = '7a0fdea5d76c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('dy_sms_student', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dy_sms_student', 'updated_date')
    op.drop_column('dy_sms_student', 'created_date')
    # ### end Alembic commands ###
