"""Add class table

Revision ID: d8b90b5696ef
Revises: 3e83b0f3efce
Create Date: 2022-07-24 14:29:02.571770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8b90b5696ef'
down_revision = '3e83b0f3efce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student', sa.Column('fav_sub', sa.String(length=50), nullable=True))
    op.drop_column('dy_sms_student', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student', sa.Column('class_id', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('dy_sms_student', 'fav_sub')
    # ### end Alembic commands ###
