"""Added column 

Revision ID: e4d3d723e71d
Revises: 236cd476b519
Create Date: 2022-07-24 14:12:08.937224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d3d723e71d'
down_revision = '236cd476b519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_student', sa.Column('class_id', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dy_sms_student', 'class_id')
    # ### end Alembic commands ###
