"""Check

Revision ID: e8cabb3ed1ca
Revises: b302f00e7b90
Create Date: 2022-07-29 23:53:52.032594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cabb3ed1ca'
down_revision = 'b302f00e7b90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
