"""Modify table

Revision ID: ed57eec99a0e
Revises: 2b4c501992e6
Create Date: 2022-07-30 08:45:05.439838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed57eec99a0e'
down_revision = '2b4c501992e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
