"""Added level table

Revision ID: f158789d66bc
Revises: 7865f2f548b5
Create Date: 2022-07-17 02:48:00.814617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f158789d66bc'
down_revision = '7865f2f548b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
