"""Added column teacher

Revision ID: fdd293bca0f9
Revises: a185a3714b8b
Create Date: 2022-07-17 02:52:20.825616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd293bca0f9'
down_revision = 'a185a3714b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dy_sms_subject', sa.Column('teacher', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dy_sms_subject', 'teacher')
    # ### end Alembic commands ###
